from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import Session
from app.core.database import get_db
from app.core.dependencies import get_current_active_user
from app.models.user import User

router = APIRouter(prefix="/recommendations", tags=["Recommendations"])


@router.get("/")
def get_recommendations(
    page: int = Query(1, ge=1),
    page_size: int = Query(10, ge=1, le=50),
    current_user: User = Depends(get_current_active_user),
    db: Session = Depends(get_db),
):
    """
    Get personalised FYP recommendations for the current user.
    Recommendations are generated by the ML service based on the user's profile.
    Returns cached results if available, otherwise triggers ML service.
    """
    # TODO: wire up ML service call + caching in sprint 2
    return {
        "message": "Recommendation engine coming in sprint 2",
        "user_id": current_user.id,
        "has_profile": current_user.profile is not None,
    }
